-- CONSULTAS
SELECT ID_USUARIO, NM_USUARIO, DS_EMAIL, DT_CRIACAO
FROM T_USUARIO
WHERE DT_CRIACAO >= SYSDATE - 30
ORDER BY DT_CRIACAO DESC;

SELECT u.NM_USUARIO,
       u.DS_EMAIL,
       r.DS_CARREIRA,
       r.DS_TRILHA,
       r.SCORE_MODELO,
       r.DT_RECOMENDACAO
FROM T_RECOMENDACAO r
JOIN T_USUARIO u ON u.ID_USUARIO = r.ID_USUARIO
ORDER BY r.DT_RECOMENDACAO DESC;

SELECT r.DS_CARREIRA,
       COUNT(*) AS QTDE_RECOMENDACOES,
       ROUND(AVG(r.SCORE_MODELO), 3) AS MEDIA_SCORE
FROM T_RECOMENDACAO r
GROUP BY r.DS_CARREIRA
ORDER BY QTDE_RECOMENDACOES DESC;

SELECT r.DS_CARREIRA,
       COUNT(*) AS QTDE,
       ROUND(AVG(r.SCORE_MODELO), 3) AS MEDIA_SCORE
FROM T_RECOMENDACAO r
JOIN T_USUARIO u ON u.ID_USUARIO = r.ID_USUARIO
WHERE r.DT_RECOMENDACAO >= SYSDATE - 15
GROUP BY r.DS_CARREIRA
HAVING AVG(r.SCORE_MODELO) >= 0.75
ORDER BY MEDIA_SCORE DESC;
