-- ===========================
-- CRIAÇÃO DO ESQUEMA (Oracle)
-- Projeto: FutureSkills (GS)
-- ===========================
CREATE TABLE T_USUARIO (
  ID_USUARIO NUMBER NOT NULL,
  NM_USUARIO VARCHAR2(80) NOT NULL,
  DS_EMAIL   VARCHAR2(120) NOT NULL,
  DS_INTERESSE VARCHAR2(50),
  DT_CRIACAO DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_T_USUARIO PRIMARY KEY (ID_USUARIO),
  CONSTRAINT UK_T_USUARIO_EMAIL UNIQUE (DS_EMAIL),
  CONSTRAINT CK_T_USUARIO_EMAIL CHECK (INSTR(DS_EMAIL, '@') > 1)
);
CREATE SEQUENCE SQ_T_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TR_T_USUARIO_BI
BEFORE INSERT ON T_USUARIO FOR EACH ROW
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN
    SELECT SQ_T_USUARIO.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
  END IF;
END;
/

CREATE TABLE T_RECOMENDACAO (
  ID_RECOMENDACAO NUMBER NOT NULL,
  ID_USUARIO NUMBER NOT NULL,
  DS_CARREIRA VARCHAR2(60) NOT NULL,
  DS_TRILHA   VARCHAR2(120) NOT NULL,
  SCORE_MODELO NUMBER(5,4) DEFAULT 0 NOT NULL,
  DT_RECOMENDACAO DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_T_RECOMENDACAO PRIMARY KEY (ID_RECOMENDACAO),
  CONSTRAINT FK_REC_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO(ID_USUARIO),
  CONSTRAINT CK_REC_SCORE CHECK (SCORE_MODELO BETWEEN 0 AND 1)
);
CREATE INDEX IX_REC_USUARIO ON T_RECOMENDACAO (ID_USUARIO);
CREATE SEQUENCE SQ_T_RECOMENDACAO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TR_T_RECOMENDACAO_BI
BEFORE INSERT ON T_RECOMENDACAO FOR EACH ROW
BEGIN
  IF :NEW.ID_RECOMENDACAO IS NULL THEN
    SELECT SQ_T_RECOMENDACAO.NEXTVAL INTO :NEW.ID_RECOMENDACAO FROM DUAL;
  END IF;
END;
/

CREATE TABLE T_MODELO_IA_LOG (
  ID_LOG NUMBER NOT NULL,
  ID_USUARIO NUMBER NOT NULL,
  NM_MODELO VARCHAR2(60) NOT NULL,
  DS_RESULTADO VARCHAR2(120),
  PROBABILIDADE NUMBER(5,4) DEFAULT 0 NOT NULL,
  DT_EXECUCAO DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_T_IA_LOG PRIMARY KEY (ID_LOG),
  CONSTRAINT FK_IA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO(ID_USUARIO),
  CONSTRAINT CK_IA_PROB CHECK (PROBABILIDADE BETWEEN 0 AND 1)
);
CREATE INDEX IX_IA_USUARIO ON T_MODELO_IA_LOG (ID_USUARIO);
CREATE SEQUENCE SQ_T_IA_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TR_T_IA_LOG_BI
BEFORE INSERT ON T_MODELO_IA_LOG FOR EACH ROW
BEGIN
  IF :NEW.ID_LOG IS NULL THEN
    SELECT SQ_T_IA_LOG.NEXTVAL INTO :NEW.ID_LOG FROM DUAL;
  END IF;
END;
/

CREATE TABLE T_CLUSTER_USUARIO (
  ID_CLUSTER NUMBER NOT NULL,
  ID_USUARIO NUMBER NOT NULL,
  CLUSTER_LABEL NUMBER NOT NULL,
  DS_CLUSTER VARCHAR2(120),
  DT_ATRIBUICAO DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_T_CLUSTER PRIMARY KEY (ID_CLUSTER),
  CONSTRAINT FK_CLUSTER_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO(ID_USUARIO),
  CONSTRAINT CK_CLUSTER_LABEL CHECK (CLUSTER_LABEL >= 0)
);
CREATE INDEX IX_CLUSTER_USUARIO ON T_CLUSTER_USUARIO (ID_USUARIO);
CREATE SEQUENCE SQ_T_CLUSTER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TR_T_CLUSTER_BI
BEFORE INSERT ON T_CLUSTER_USUARIO FOR EACH ROW
BEGIN
  IF :NEW.ID_CLUSTER IS NULL THEN
    SELECT SQ_T_CLUSTER.NEXTVAL INTO :NEW.ID_CLUSTER FROM DUAL;
  END IF;
END;
/